#ifndef __IPCLINUX_MPI_VDECSOFT_H__
#define __IPCLINUX_MPI_VDECSOFT_H__

#include "mm_comm_vdecsoft.h"

ERRORTYPE AW_MPI_VDECSOFT_CreateChn(VDECSOFT_CHN VdstChn, const VDECSOFT_CHN_ATTR_S *pstAttr);
ERRORTYPE AW_MPI_VDECSOFT_DestroyChn(VDECSOFT_CHN VdstChn);

ERRORTYPE AW_MPI_VDECSOFT_StartRecvStream(VDECSOFT_CHN VdstChn);
ERRORTYPE AW_MPI_VDECSOFT_StopRecvStream(VDECSOFT_CHN VdstChn);

ERRORTYPE AW_MPI_VDECSOFT_SendStream(VDECSOFT_CHN VdstChn, const VDECSOFT_STREAM_S *pStream,
                                     int nMilliSec);

ERRORTYPE AW_MPI_VDECSOFT_GetImage(VDECSOFT_CHN VdstChn, VDECSOFT_FRAME_INFO_S *pFrameInfo);
ERRORTYPE AW_MPI_VDECSOFT_ReleaseImage(VDECSOFT_CHN VdstChn, VDECSOFT_FRAME_INFO_S *pFrameInfo);

ERRORTYPE AW_MPI_VDECSOFT_ResetChn(VDECSOFT_CHN VdstChn);
ERRORTYPE AW_MPI_VDECSOFT_GetChnAttr(VDECSOFT_CHN VdstChn, VDECSOFT_CHN_ATTR_S *pstAttr);
ERRORTYPE AW_MPI_VDECSOFT_RegisterCallback(VDECSOFT_CHN VdstChn, MPPCallbackInfo *pCallback);
ERRORTYPE AW_MPI_VDECSOFT_SetStreamEof(VDECSOFT_CHN VdstChn, BOOL bEofFlag);
ERRORTYPE AW_MPI_VDECSOFT_Seek(VDECSOFT_CHN VdstChn);

#endif /* __IPCLINUX_MPI_VDECSOFT_H__ */