/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __OS_NET_UTILS_H__
#define __OS_NET_UTILS_H__
#include <stdio.h>
#include <stdlib.h>

typedef enum {
    OS_NET_STATUS_OK = 0,
    OS_NET_STATUS_FAILED,
    OS_NET_STATUS_NOT_READY,
    OS_NET_STATUS_BUSY,
    OS_NET_STATUS_PARAM_INVALID,
    OS_NET_STATUS_NOMEM,
} os_net_status_t;

#define OS_NET_PRINTF printf

#define OS_NET_OS_LOG(fmt, arg...)                                                                 \
    do {                                                                                           \
        OS_NET_PRINTF(fmt "\n", ##arg);                                                            \
    } while (0)

#define OS_NET_INFO(fmt, arg...) OS_NET_OS_LOG("[ACT I][%s,%d]" fmt, __func__, __LINE__, ##arg)
#define OS_NET_DEBUG(fmt, arg...) OS_NET_OS_LOG("[ACT D][%s,%d]" fmt, __func__, __LINE__, ##arg)
#define OS_NET_ERROR(fmt, arg...) OS_NET_OS_LOG("[ACT E][%s,%d]" fmt, __func__, __LINE__, ##arg)
#define OS_NET_WARN(fmt, arg...) OS_NET_OS_LOG("[ACT W][%s,%d]" fmt, __func__, __LINE__, ##arg)
#define OS_NET_DUMP(fmt, arg...) //OS_NET_OS_LOG("[ACT DUMP][%s,%d]"fmt,__func__,__LINE__,##arg)
#define OS_NET_EXCESSIVE(fmt, arg...) //OS_NET_OS_LOG("[ACT EX][%s,%d]"fmt,__func__,__LINE__,##arg)

#define OS_NET_TASK_POST_BLOCKING (0xffffffffU)
#define OS_NET_TASK_POST_NO_BLOCKING (0)
#define OS_NET_WAIT_FOREVER (0xffffffffU)
#endif
