/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the people's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef _CONFIGOPTION_H_
#define _CONFIGOPTION_H_

// option for CDXCFG_FILE_SYSTEM.
#define OPTION_FILE_SYSTEM_LINUX_VFS    (0)
#define OPTION_FILE_SYSTEM_DIRECT_FATFS (1)
#define OPTION_FILE_SYSTEM_DIRECT_IO    (2)

//option for CDXCFG_HW_DISPLAY
#define OPTION_HW_DISPLAY_ENABLE    (1)
#define OPTION_HW_DISPLAY_DISABLE   (0)

//option for MPPCFG_VI
#define OPTION_VI_ENABLE    (1)
#define OPTION_VI_DISABLE   (0)

//option for MPPCFG_VO
#define OPTION_VO_ENABLE    (1)
#define OPTION_VO_DISABLE   (0)

//option for MPPCFG_TEXTENC
#define OPTION_TEXTENC_ENABLE (1)
#define OPTION_TEXTENC_DISABLE (0)

//option for MPPCFG_VENC
#define OPTION_VENC_ENABLE (1)
#define OPTION_VENC_DISABLE (0)

//option for MPPCFG_VDEC
#define OPTION_VDEC_ENABLE (1)
#define OPTION_VDEC_DISABLE (0)

//option for MPPCFG_VDECSOFT
#define OPTION_VDECSOFT_ENABLE (1)
#define OPTION_VDECSOFT_DISABLE (0)

//option for MPPCFG_AIO
#define OPTION_AIO_ENABLE    (1)
#define OPTION_AIO_DISABLE   (0)

//option for MPPCFG_AIO_LIB
#define OPTION_AIO_LIBRARY_ALSA (0)
#define OPTION_AIO_LIBRARY_AUDIOSYSTEM (1)

//option for MPPCFG_AENC
#define OPTION_AENC_ENABLE (1)
#define OPTION_AENC_DISABLE (0)

//option for MPPCFG_ADEC
#define OPTION_ADEC_ENABLE (1)
#define OPTION_ADEC_DISABLE (0)

//option for MPPCFG_MUXER
#define OPTION_MUXER_ENABLE    (1)
#define OPTION_MUXER_DISABLE   (0)

//option for MPPCFG_DEMUXER
#define OPTION_DEMUXER_ENABLE    (1)
#define OPTION_DEMUXER_DISABLE   (0)

//option for MPPCFG_ISE
#define OPTION_ISE_ENABLE    (1)
#define OPTION_ISE_DISABLE   (0)

//option for MPPCFG_ISE_MO
#define OPTION_ISE_MO_ENABLE     (1)
#define OPTION_ISE_MO_DISABLE    (0)

//option for MPPCFG_ISE_GDC
#define OPTION_ISE_GDC_ENABLE    (1)
#define OPTION_ISE_GDC_DISABLE   (0)

//option for MPPCFG_EIS
#define OPTION_EIS_ENABLE    (1)
#define OPTION_EIS_DISABLE   (0)

//option for MPPCFG_AEC
#define OPTION_AEC_ENABLE    (1)
#define OPTION_AEC_DISABLE   (0)

#define OPTION_ANS_ENABLE    (1)
#define OPTION_ANS_DISABLE   (0)

#define OPTION_SOFTDRC_ENABLE    (1)
#define OPTION_SOFTDRC_DISABLE   (0)

#define OPTION_AGC_ENABLE    (1)
#define OPTION_AGC_DISABLE   (0)

//option for MPPCFG_AEC_LIB
#define OPTION_AEC_LIBRARY_WEBRTC (0)
#define OPTION_AEC_LIBRARY_UVOICE (1)

//option for MPPCFG_ANS_LIB
#define OPTION_ANS_LIBRARY_WEBRTC (0)
#define OPTION_ANS_LIBRARY_LSTM (1)
#define OPTION_ANS_LIBRARY_NOSC (2)

//option for MPPCFG_AGC_LIB
#define OPTION_AGC_LIBRARY_WEBRTC (0)
#define OPTION_AGC_LIBRARY_AGCFLOAT (1)

//option for MPPCFG_GPS_PACK_METHOD
#define OPTION_GPS_PACK_IN_TRACK (0)
#define OPTION_GPS_PACK_IN_MDAT (1)

/*
// option for CDXCFG_GPU_TYPE
#define OPTION_GPU_TYPE_MALI    (0)
#define OPTION_GPU_TYPE_IMG     (1)
#define OPTION_GPU_TYPE_NONE    (255)

// option for CDXCFG_VE_NATIVE_OUTPUT_FORMAT
#define OPTION_VE_NATIVE_OUTPUT_FORMAT_YV12    (0)
#define OPTION_VE_NATIVE_OUTPUT_FORMAT_MB32    (1)

//property key/value for WRITE_FILE_METHOD
#define PROP_KEY_WRITE_FILE_METHOD   "media.cedarx.WRITE_FILE_METHOD"
#define PROP_VALUE_FS_THREAD_CACHE  "FS_THREAD_CACHE"
#define PROP_VALUE_FS_SIMPLE_CACHE  "FS_SIMPLE_CACHE"
#define PROP_VALUE_FS_NO_CACHE      "FS_NO_CACHE"

//property key/value for simple cache size
#define PROP_KEY_FS_SIMPLE_CACHE_SIZE   "media.cedarx.cache_size"

//property key/value for REC_VBV_TIME
#define PROP_KEY_REC_VBV_TIME   "media.cedarx.REC_VBV_TIME"

//property key/value for FrameInterval, unit:ms
#define PROP_KEY_PLAY_FRAME_INTERVAL   "media.cedarx.PlayFrameInterval"

//property key/value for output resolution constraint
#define PROP_KEY_CONSTRAINT_RES  "media.cedarx.cons_res"

//property key/value for video encode color space
#define PROP_KEY_ENCODE_COLOR_SPACE   "media.cedarx.EncodeColorSpace"
#define PROP_VALUE_BT601 "BT601"
#define PROP_VALUE_FOLLOW_SOURCE "FollowSource"
*/

#endif  /* _CONFIGOPTION_H_ */

